services:
  producer-api:
    container_name: producer-service
    image: producer.api
    build:
      context: .
      dockerfile: Producer.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - kafka

  consumer-api:
    container_name: consumer-service
    image: consumer.api
    build:
      context: .
      dockerfile: Consumer.Api/Dockerfile
    ports:
      - "6000:8080"
    depends_on:
      - kafka

  consumer-api-instance-1:
    container_name: consumer-service-instance-1
    image: consumer.api
    build:
      context: .
      dockerfile: Consumer.Api/Dockerfile
    ports:
      - "6001:8080"
    depends_on:
      - kafka
      
  consumer-api-instance-2:
    container_name: consumer-service-instance-2
    image: consumer.api
    build:
      context: .
      dockerfile: Consumer.Api/Dockerfile
    ports:
      - "6002:8080"
    depends_on:
      - kafka
        
  kafka:
    container_name: broker
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=3